export const TYPE = {
    SUCCESS: "success",
    ERROR: "error",
    WARNING: "warning",
    FULLTIME: "FULLTIME",
    PARTTIME:  "PARTTIME",
    INTERNSHIP: "INTERNSHIP",

    MON: 'MON',
    TUE: 'TUE',
    WED: 'WED',
    THU: 'THU',
    FRI: 'FRI',
    SAT: 'SAT',
    SUN: 'SUN',

    MOR: 'MOR',
    AFT: 'AFT',
    EVN: 'EVN',
    
    TOP: 'TOP',
    HIGHLIGHT: 'HIGHLIGHT',

    EVENT: 'EVENT',
    NORMAL: 'NORMAL',

    DESCRIPTION: "description",
    PERSON: "person",
    SKILLS: "skills",
    LANGUAGE_SKILL: "languageSkill",
    EDUCATION: "eduction",
    TOOLS: "tools",
    EXPERIENCE: "experience",
    PICTURE: "picture",
    DEFAULT_IMAGE: "https://i.vdoc.vn/data/image/2019/07/15/anh-bia-dep-cay-coi.jpg",
    DEFAULT_AVATAR: "https://www.kindpng.com/picc/m/269-2697881_computer-icons-user-clip-art-transparent-png-icon.png",
    AVATAR: "avatar",
    COVER: "cover",
    FACEBOOK: "facebook",
}